# Generated by Django 5.2.5 on 2025-09-05 22:35

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Profil', 'verbose_name_plural': 'Profils'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, help_text='Adresse complète', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Image JPG, PNG ou GIF. Taille max: 2MB', null=True, upload_to=profiles.models.avatar_upload_path, verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: +33 1 23 45 67 89', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Code postal français (5 chiffres)', max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='receive_newsletters',
            field=models.BooleanField(default=True, help_text='Recevoir les actualités et promotions par email', verbose_name='Recevoir la newsletter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='receive_notifications',
            field=models.BooleanField(default=True, help_text='Recevoir les notifications importantes par email', verbose_name='Recevoir les notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
    ]
