# Generated by Django 5.2.5 on 2025-09-02 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_projet', models.CharField(choices=[('peinture_interieure', 'Peinture Intérieure'), ('peinture_exterieure', 'Peinture Extérieure'), ('decoration', 'Décoration'), ('renovation', 'Rénovation'), ('revetement_mural', 'Revêtement Mural'), ('commercial', 'Peinture Commerciale'), ('autre', 'Autre')], max_length=50, verbose_name='Type de projet')),
                ('description', models.TextField(help_text='Décrivez votre projet en détail', verbose_name='Description')),
                ('surface', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Surface (m²)')),
                ('date_debut_souhaitee', models.DateField(blank=True, null=True, verbose_name='Date de début souhaitée')),
                ('date_fin_souhaitee', models.DateField(blank=True, null=True, verbose_name='Date de fin souhaitée')),
                ('urgence', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('elevee', 'Élevée'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Urgence')),
                ('adresse_travaux', models.CharField(default='À définir', help_text='Adresse où les travaux seront réalisés', max_length=255, verbose_name='Adresse des travaux')),
                ('complement_adresse', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget estimé (€)')),
                ('status', models.CharField(choices=[('en_reflexion', 'En réflexion'), ('devis_demande', 'Devis demandé'), ('devis_recu', 'Devis reçu'), ('accepte', 'Accepté'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_reflexion', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-created_at'],
            },
        ),
    ]
