# Generated by Django 5.2.5 on 2025-09-05 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Titre court et descriptif du projet', max_length=200, verbose_name='Titre du projet')),
                ('type_projet', models.CharField(choices=[('peinture_interieure', 'Peinture Intérieure'), ('peinture_exterieure', 'Peinture Extérieure'), ('decoration', 'Décoration'), ('renovation', 'Rénovation'), ('revetement_mural', 'Revêtement Mural'), ('commercial', 'Peinture Commerciale'), ('autre', 'Autre')], db_index=True, max_length=50, verbose_name='Type de projet')),
                ('description', models.TextField(help_text='Description détaillée du projet', verbose_name='Description')),
                ('surface', models.DecimalField(blank=True, decimal_places=2, help_text='Surface à traiter en mètres carrés', max_digits=8, null=True, verbose_name='Surface (m²)')),
                ('nombre_pieces', models.PositiveIntegerField(blank=True, help_text='Nombre de pièces concernées par le projet', null=True, verbose_name='Nombre de pièces')),
                ('date_debut_souhaitee', models.DateField(blank=True, help_text='Date à laquelle vous souhaitez commencer les travaux', null=True, verbose_name='Date de début souhaitée')),
                ('date_fin_souhaitee', models.DateField(blank=True, help_text='Date à laquelle vous souhaitez finir les travaux', null=True, verbose_name='Date de fin souhaitée')),
                ('date_debut_effective', models.DateField(blank=True, null=True, verbose_name='Date de début effective')),
                ('date_fin_effective', models.DateField(blank=True, null=True, verbose_name='Date de fin effective')),
                ('priority', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('elevee', 'Élevée'), ('urgente', 'Urgente')], db_index=True, default='normale', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_reflexion', 'En réflexion'), ('devis_demande', 'Devis demandé'), ('devis_recu', 'Devis reçu'), ('devis_approuve', 'Devis approuvé'), ('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('en_attente', 'En attente')], db_index=True, default='brouillon', max_length=20, verbose_name='Statut')),
                ('adresse_travaux', models.CharField(help_text='Adresse où les travaux seront réalisés', max_length=255, verbose_name='Adresse des travaux')),
                ('complement_adresse', models.CharField(blank=True, help_text='Appartement, étage, bâtiment, etc.', max_length=255, verbose_name="Complément d'adresse")),
                ('code_postal', models.CharField(db_index=True, max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(db_index=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=2, help_text='Budget approximatif pour le projet', max_digits=10, null=True, verbose_name='Budget estimé (€)')),
                ('devis_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant du devis (€)')),
                ('notes_client', models.TextField(blank=True, help_text='Notes et remarques du client', verbose_name='Notes du client')),
                ('notes_internes', models.TextField(blank=True, help_text="Notes internes pour l'équipe", verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_projects', 'Peut voir tous les projets'), ('can_manage_projects', 'Peut gérer tous les projets'), ('can_approve_quotes', 'Peut approuver les devis')],
                'indexes': [models.Index(fields=['user', 'status'], name='projects_pr_user_id_40c3f7_idx'), models.Index(fields=['type_projet', 'status'], name='projects_pr_type_pr_371ac0_idx'), models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'), models.Index(fields=['priority', 'status'], name='projects_pr_priorit_17637b_idx')],
            },
        ),
    ]
