# Generated by Django 5.2.5 on 2025-09-06 11:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Référence')),
                ('title', models.CharField(blank=True, help_text='Titre descriptif du devis', max_length=200, verbose_name='Titre du devis')),
                ('description', models.TextField(blank=True, help_text='Description des travaux proposés', verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_sent', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_viewed', models.DateTimeField(blank=True, null=True, verbose_name='Date de consultation')),
                ('date_response', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('date_expiry', models.DateField(help_text='Date limite de validité du devis', verbose_name="Date d'expiration")),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('vu', 'Vu par le client'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré'), ('annule', 'Annulé')], db_index=True, default='brouillon', max_length=20, verbose_name='Statut')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sous-total (€)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant TVA (€)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total TTC (€)')),
                ('terms_conditions', models.TextField(blank=True, help_text='Conditions générales de vente et modalités', verbose_name='Conditions générales')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles', verbose_name='Notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DevisHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Créé'), ('sent', 'Envoyé'), ('viewed', 'Consulté'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('modified', 'Modifié'), ('cancelled', 'Annulé')], max_length=20, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('notes', models.TextField(blank=True, help_text='Notes sur cette action', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Historique devis',
                'verbose_name_plural': 'Historiques devis',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DevisLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantité de ce produit', max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix unitaire au moment du devis', max_digits=10, verbose_name='Prix unitaire (€)')),
                ('total', models.DecimalField(decimal_places=2, help_text='Montant total de cette ligne', max_digits=10, verbose_name='Total ligne (€)')),
                ('description', models.TextField(blank=True, help_text='Description spécifique pour cette ligne', verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le devis", verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Code unique du produit', max_length=50, unique=True, verbose_name='Code produit')),
                ('name', models.CharField(help_text='Nom commercial du produit', max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du produit', verbose_name='Description')),
                ('type_product', models.CharField(choices=[('peinture', 'Peinture'), ('sous_couche', 'Sous-couche'), ('main_oeuvre', "Main d'œuvre"), ('materiel', 'Matériel'), ('equipement', 'Équipement'), ('service', 'Service'), ('autre', 'Autre')], db_index=True, max_length=20, verbose_name='Type de produit')),
                ('unit', models.CharField(choices=[('m2', 'm²'), ('ml', 'ml'), ('piece', 'Pièce'), ('heure', 'Heure'), ('jour', 'Jour'), ('litre', 'Litre'), ('kg', 'Kg'), ('forfait', 'Forfait')], help_text='Unité de mesure pour ce produit', max_length=20, verbose_name='Unité')),
                ('price_unit', models.DecimalField(decimal_places=2, help_text='Prix par unité', max_digits=10, verbose_name='Prix unitaire (€)')),
                ('is_active', models.BooleanField(default=True, help_text='Produit disponible pour les devis', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['type_product', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget_estime',
        ),
        migrations.RemoveField(
            model_name='project',
            name='devis_montant',
        ),
        migrations.RemoveField(
            model_name='project',
            name='surface',
        ),
        migrations.AddField(
            model_name='project',
            name='acces_difficile',
            field=models.BooleanField(default=False, help_text='Accès difficile ou contraintes particulières', verbose_name='Accès difficile'),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget maximum envisagé', max_digits=10, null=True, verbose_name='Budget maximum (€)'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget minimum envisagé', max_digits=10, null=True, verbose_name='Budget minimum (€)'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_nom',
            field=models.CharField(blank=True, help_text='Personne à contacter sur le lieu des travaux', max_length=200, verbose_name='Nom du contact sur site'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_telephone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone du contact sur site', max_length=20, verbose_name='Téléphone du contact'),
        ),
        migrations.AddField(
            model_name='project',
            name='contraintes_horaires',
            field=models.TextField(blank=True, help_text="Contraintes d'horaires ou de planning", verbose_name='Contraintes horaires'),
        ),
        migrations.AddField(
            model_name='project',
            name='couleurs_souhaitees',
            field=models.JSONField(blank=True, default=dict, help_text='Couleurs par zone (murs, plafond, etc.)', verbose_name='Couleurs souhaitées'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_debut_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début prévue'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_fin_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin prévue'),
        ),
        migrations.AddField(
            model_name='project',
            name='etat_support',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('abime', 'Abîmé')], default='bon', help_text='État actuel des surfaces à traiter', max_length=20, verbose_name='État du support'),
        ),
        migrations.AddField(
            model_name='project',
            name='hauteur_sous_plafond',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hauteur sous plafond en mètres', max_digits=4, null=True, verbose_name='Hauteur sous plafond (m)'),
        ),
        migrations.AddField(
            model_name='project',
            name='materiaux_specifiques',
            field=models.TextField(blank=True, help_text='Matériaux ou marques spécifiques demandés', verbose_name='Matériaux spécifiques'),
        ),
        migrations.AddField(
            model_name='project',
            name='preparation_necessaire',
            field=models.TextField(blank=True, help_text='Travaux de préparation requis', verbose_name='Préparation nécessaire'),
        ),
        migrations.AddField(
            model_name='project',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence unique générée automatiquement', max_length=20, unique=True, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='project',
            name='surface_murs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface des murs à peindre', max_digits=8, null=True, verbose_name='Surface murs (m²)'),
        ),
        migrations.AddField(
            model_name='project',
            name='surface_plafond',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Surface du plafond à peindre', max_digits=8, null=True, verbose_name='Surface plafond (m²)'),
        ),
        migrations.AddField(
            model_name='project',
            name='surface_totale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Surface totale à traiter', max_digits=8, verbose_name='Surface totale (m²)'),
        ),
        migrations.AddField(
            model_name='project',
            name='type_finition',
            field=models.CharField(choices=[('mat', 'Mat'), ('satin', 'Satin'), ('semi_brillant', 'Semi-brillant'), ('brillant', 'Brillant'), ('texture', 'Texturé')], default='mat', help_text='Type de finition souhaitée', max_length=20, verbose_name='Type de finition'),
        ),
        migrations.AddField(
            model_name='project',
            name='types_pieces',
            field=models.JSONField(blank=True, default=list, help_text='Liste des types de pièces concernées', verbose_name='Types de pièces'),
        ),
        migrations.AlterField(
            model_name='project',
            name='adresse_travaux',
            field=models.CharField(default='', help_text='Adresse complète où les travaux seront réalisés', max_length=255, verbose_name='Adresse des travaux'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_debut_souhaitee',
            field=models.DateField(blank=True, help_text='Date souhaitée pour commencer les travaux', null=True, verbose_name='Date de début souhaitée'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_fin_souhaitee',
            field=models.DateField(blank=True, help_text='Date souhaitée pour terminer les travaux', null=True, verbose_name='Date de fin souhaitée'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Description complète du projet et des attentes', verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nombre_pieces',
            field=models.PositiveIntegerField(default=1, help_text='Nombre total de pièces concernées', verbose_name='Nombre de pièces'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes_client',
            field=models.TextField(blank=True, help_text='Remarques et demandes spécifiques du client', verbose_name='Notes du client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('en_examen', 'En examen'), ('devis_demande', 'Devis demandé'), ('devis_envoye', 'Devis envoyé'), ('devis_accepte', 'Devis accepté'), ('devis_refuse', 'Devis refusé'), ('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('en_attente', 'En attente')], db_index=True, default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, help_text='Titre descriptif du projet', max_length=200, verbose_name='Titre du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_projet',
            field=models.CharField(choices=[('peinture_interieure', 'Peinture Intérieure'), ('peinture_exterieure', 'Peinture Extérieure'), ('decoration', 'Décoration'), ('renovation', 'Rénovation'), ('revetement_mural', 'Revêtement Mural'), ('commercial', 'Peinture Commerciale'), ('residentiel', 'Résidentiel'), ('autre', 'Autre')], db_index=True, max_length=50, verbose_name='Type de projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['reference'], name='projects_pr_referen_43c609_idx'),
        ),
        migrations.AddField(
            model_name='devis',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_devis', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='devis',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='devishistory',
            name='devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projects.devis', verbose_name='Devis'),
        ),
        migrations.AddField(
            model_name='devishistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='devisline',
            name='devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='projects.devis', verbose_name='Devis'),
        ),
        migrations.AddField(
            model_name='devisline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.product', verbose_name='Produit'),
        ),
    ]
