# Generated by Django 5.2.5 on 2025-09-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RemoveField(
            model_name='devis',
            name='date_response',
        ),
    ]
