# Generated by Django 5.2.5 on 2025-09-03 20:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('account_type', models.CharField(choices=[('CLIENT', 'Client'), ('COLLABORATOR', 'Collaborateur'), ('ADMINISTRATOR', 'Administrateur')], default='CLIENT', help_text="Définit le niveau d'accès de l'utilisateur", max_length=20, verbose_name='type de compte')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('verification_token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Token para verificação de email', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Indica se o email foi verificado', verbose_name='email verified')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='Último endereço IP de login', null=True, verbose_name='last login IP')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Número de tentativas de login falhadas', verbose_name='failed login attempts')),
                ('last_failed_login', models.DateTimeField(blank=True, help_text='Data da última tentativa de login falhada', null=True, verbose_name='last failed login')),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='Data da última alteração de senha', null=True, verbose_name='password changed at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
                'permissions': [('can_view_dashboard', 'Peut afficher le tableau de bord'), ('can_manage_users', 'Peut gérer les utilisateurs')],
                'indexes': [models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'), models.Index(fields=['account_type'], name='accounts_us_account_28efcc_idx'), models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx')],
            },
        ),
    ]
